---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r setup}
library(tidyverse)
library(phytools)
library(caper)
library(here)
library(geiger)
library(emmeans)
```

```{r}
vertdata <- read_csv("All_Vert_Data.csv")
```

```{r}
head(vertdata)
```
```{r}
vertdata_sum <-
  vertdata %>%
  group_by(FullName, Genus, Species, Body.Shape, Habitat) %>%
  dplyr::select(FullName, Genus, Species, 
                d, CBL, alpha_Ant, alpha_Pos, Body.Shape, Habitat, Tip) %>%
  rename(alphaAnt = alpha_Ant, alphaPos = alpha_Pos) %>%
  summarize_at(vars(d, CBL, alphaAnt, alphaPos), list(mn = mean, max = max)) %>%
  ungroup()
```

```{r}
vertdata_sum <-
  vertdata_sum %>%
  column_to_rownames(var="FullName")
```

```{r}
vertdata_sum
```

```{r}
treefile <- '12862_2017_958_MOESM2_ESM.tre'
```

```{r}
tree <- read.tree(here('..', treefile))
```

```{r}
check <- name.check(tree, vertdata_sum)
check$data_not_tree
```

```{r}
tree_trimmed <- drop.tip(tree, check$tree_not_data)
```

```{r}
name.check(tree_trimmed, vertdata_sum)
```

```{r}
vertdata_sum <-
  vertdata_sum %>%
  rownames_to_column(var = "FullName")
```

```{r}
tree_trimmed
```

```{r}
tree_trimmed$node.label <- NULL
```


```{r}
comp.data <- comparative.data(tree_trimmed, vertdata_sum, names.col="FullName", vcv.dim=2,
                              warn.dropped=TRUE)
```

```{r}
comp.data
```

```{r}
m1 <- pgls(d_max ~ Habitat, data = comp.data)
```

```{r}
summary(m1)
```

```{r}
anova(m1)
```
ANOVA of d_max based on habitat is significant.

```{r}
m2 <- pgls(d_mn ~ Habitat, data = comp.data)

summary(m2)
```

```{r}
anova(m2)
```
But why isn't ANOVA of d_mean based on habitat significant? 

```{r}
c1 <- pgls(CBL_max ~ Habitat, data = comp.data)

summary(c1)
```

```{r}
anova(c1)
```


```{r}
c2 <- pgls(CBL_mn ~ Habitat, data = comp.data)

summary(c2)
```

```{r}
anova(c2)
```

```{r}
a1 <- pgls(alphaPos_max ~ Habitat, data = comp.data)

summary(a1)
```
alphaPos is significantly different for pelagic, which is promising! 

```{r}
anova(a1)
```
This is like so close to being significant.

```{r}
a2 <- pgls(alphaPos_mn ~ Habitat, data = comp.data)

summary(a2)
```
I wonder why the alphaPos max and mean are so different 

```{r}
anova(a2)
```
