---
title: "Flexibility/Vertebral Measurement Comparison"
output: html_notebook
---

En = transverse flexibility
Qn = cross sectional area ratios
Gn = cross sectional shape indices
Vn = # of elastic joints in axial skeleton

```{r}
library(tidyverse)
library(ggplot2)
library(Hmisc)
library(rfishbase)
```

#Load in Vertebrae Measurements and Aleyev Flexibility Data
```{r}
newvertmeas <- read.csv("AllVertMeasurements.csv", header = TRUE, skip = 1)

newvertmeas
```

```{r}
newvertmeasmean <- newvertmeas %>%
  group_by(Species, Indiv) %>%
  select(SL, CBL, d, alpha_Pos, alpha_Ant, D_Pos, D_Ant) %>%
  summarize_all(mean, na.rm=TRUE) %>%
  ungroup()

newvertmeasmean
```


```{r}
vertflex <- read.csv("Aleyev Table 6 Digitization.csv")

vertflex
```

#Take Mean for Vertebrae Measurements and Flexibility Data
```{r}
vertflexmean <- vertflex %>%
  group_by(Species) %>% 
  select(En, Qn, Gn, Vn) %>%
  summarize_all(mean, na.rm = TRUE) %>%
  ungroup()

vertflexmean
```

#Merge the two tables and take the mean of NewVertMeas
```{r}

```

#Preliminary Plots for VertMeas/En Comparisons
```{r}
ggplot()
```






