---
title: "get_fish_info"
output: html_notebook
---

Documentation for rfishbase: (https://cran.r-project.org/web/packages/rfishbase/vignettes/tutorial.html)

# Load libraries

Load the libraries we need.

```{r}
library(rfishbase)
library(tidyverse)
```

# Test a few species

NB: Don't call the list of species `species` because that's the function we need to call in rfishbase to get information.
```{r}
fish <- c("Anoplogaster cornuta",
             "Platichthys stellatus")
```

```{r}
validate_names(fish)
```

```{r}
fishdata <- species(fish)
```

```{r}
str(fishdata)
```

```{r}
dat <- species(fish, fields=c("BodyShapeI", "DepthRangeShallow", "DepthRangeDeep", "DepthRangeComShallow", "DepthRangeComDeep", "Length", "CommonLength", "Weight", "DemersPelag"))
```

```{r}
dat
```

# Load species from CSV file
```{r}
filename <- "../Merged Data/VertMeasurements_Shape-Habitat.csv"
```

```{r}
vertmeas <- read.csv(filename, colClasses = c("Species"="character"))

vertmeas
```

```{r}
str(vertmeas)
```

```{r}
#Idea for removing underscores, looked at https://swcarpentry.github.io/r-novice-inflammation/11-supp-read-write-csv/index.html

vertmeas <- mutate(vertmeas,
                   Species = sub("_", " ", Species)) #ifelse(as.character(Species)=='Alectis_ciliaris', 'Dana', as.character(Species)))
# vertmeas$Species <- as.factor(vertmeas$Species)
```

```{r}
vertmeas$Species
```

```{r}
fish <- vertmeas %>% distinct(Species)
```

```{r}
fish$Species
```

New challenge: Find the missing species and correct them

```{r}
validate_names(fish$Species)
```

```{r}
fishbasedata <- species(fish, fields=c("BodyShapeI", "DepthRangeShallow", "DepthRangeDeep", "DepthRangeComShallow", "DepthRangeComDeep", "Length", "CommonLength", "Weight", "DemersPelag"))
```

