---
title: "ggtree attempt"
output: html_notebook
---


```{r}
library(ggplot2)
library(ape)
library(ggtree) 
library(rfishbase)
library(Hmisc)
library(phytools)
library(here)
library(geiger)
library(nlme)
library(patchwork)
library(emmeans)
library(multcompView)
library(readxl)
library(plotly) 
library(ggthemes) 
library(naniar)
library(dplyr)
library(tidyverse)
library(car)
library(ggbeeswarm)
```

```{r}
vertsheet <- read.csv("MasterVert_Measurements.csv")
vertsheet
```

```{r}
treefile <- '12862_2017_958_MOESM2_ESM.tre'
```

```{r}
tree <- read.tree(here('..', treefile))
```

```{r}
plotTree(tree)
```

```{r}
allspecies <- as.data.frame(tree$tip.label, stringsAsFactors = FALSE) 
colnames(allspecies) <- c('FullName')

allspecies
```

```{r}
allspecies <- 
  allspecies %>% separate(FullName, sep='_', into=c('Family', 'Genus', 'Species'), 
                          extra='drop', remove=FALSE)

allspecies
```

```{r}
allspecies$Tip <- seq_len(nrow(allspecies))
```

```{r}
fullvertsheet <- vertsheet %>%
  group_by(Species, Body.Shape, Habitat_Friedman, Habitat) %>%
  summarize_at(vars(d, CBL, D_Pos, D_Ant, alpha_Pos, alpha_Ant, d_BW, D_Pos_BW, D_Ant_BW, SL.Max_BW, d_normCBL), 
               list(mean = ~mean(.x, na.rm = TRUE),
                    max = ~max(.x, na.rm = TRUE),
                    min = ~min(.x, na.rm = TRUE)))%>%
  ungroup() %>%
  separate(Species, sep='_', into=c("Genus", "Species"))
               
fullvertsheet
```

```{r}
fullvertsheet.tree <- left_join(fullvertsheet, allspecies, by=c("Genus", "Species"))
fullvertsheet.tree
```

```{r}
fullvertsheet.bygenus <- left_join(filter(fullvertsheet.tree, is.na(Tip)),
          distinct(allspecies, Genus, .keep_all=TRUE), by=c("Genus")) %>%
  transmute(Genus=Genus, Species=Species.x, Family=Family.y, MatchSpecies=Species.y, Tip=Tip.y) 

fullvertsheet.bygenus
```

```{r}
left_join(fullvertsheet.tree, fullvertsheet.bygenus,
          by = c("Genus","Species","Family")) %>%
  mutate(Tip = coalesce(Tip.x, Tip.y),
         MatchSpecies = coalesce(MatchSpecies, Species)) %>%
  select(-Tip.x, -Tip.y) %>%
  filter(!is.na(Tip)) ->
  fullvertsheet.all

fullvertsheet.all
```

```{r}
fullvertsheet.all <- column_to_rownames(fullvertsheet.all, var="FullName")

fullvertsheet.all
```

```{r}
verttree <- keep.tip(tree, tip=as.vector(fullvertsheet.all$Tip))
```

```{r}
plotTree(verttree)
```


```{r}
treefig <- ggtree(verttree)+
  geom_tiplab() +
  geom_tree(aes(color=Habitat))
treefig
```


