---
title: "PGLS with Full Data Set"
output: html_notebook
---


#Load in packages 
```{r}
library(rfishbase)
library (ggplot2)
library(Hmisc)
library(phytools)
library(here)
library(ape)
library(geiger)
library(nlme)
library(patchwork)
library(emmeans)
library(multcompView)
library(readxl)
library(plotly) 
library(ggthemes) 
library(naniar)
library(dplyr)
library(tidyverse)
```

#Load in csv
```{r}
fullvertmeas <- read.csv("MasterVert_Measurements.csv")
head(fullvertmeas)
```

#Load in phylogenetic information
```{r}
treefile <- '12862_2017_958_MOESM2_ESM.tre'
```

```{r}
tree <- read.tree(here('..', treefile))
```

```{r}
plotTree(tree)
```

```{r}
allspecies <- as.data.frame(tree$tip.label, stringsAsFactors = FALSE) 
colnames(allspecies) <- c('FullName')

allspecies
```

```{r}
allspecies <- 
  allspecies %>% separate(FullName, sep='_', into=c('Family', 'Genus', 'Species'), 
                          extra='drop', remove=FALSE)

allspecies
```

```{r}
allspecies$Tip <- seq_len(nrow(allspecies))
```

```{r}
fullvertmeas.mean <- vertmeasall %>%
  group_by(Species, Body.Shape, Habitat_Friedman, Habitat) %>%
  summarize_at(vars(d, CBL, D_Pos, D_Ant, alpha_Pos, alpha_Ant, d_BW, D_Pos_BW, D_Ant_BW), funs(mean, max, na.rm = TRUE) %>%
  ungroup() %>%
  separate(Species, sep='_', into=c("Genus", "Species")))
               
fullvertmeas.mean
```

```{r}
fullvertmeas.species <- left_join(fullvertmeas.mean, allspecies, by=c("Genus", "Species"))
fullvertmeas.species
```

```{r}
fullvertmeas.bygenus <- left_join(filter(fullvertmeas.species, is.na(Tip)),
          distinct(allspecies, Genus, .keep_all=TRUE), by=c("Genus")) %>%
  transmute(Genus=Genus, Species=Species.x, Family=Family.y, MatchSpecies=Species.y, Tip=Tip.y) 

fullvertmeas.bygenus
```

```{r}
left_join(fullvertmeas.species, fullvertmeas.bygenus,
          by = c("Genus","Species","Family")) %>%
  mutate(Tip = coalesce(Tip.x, Tip.y),
         MatchSpecies = coalesce(MatchSpecies, Species)) %>%
  select(-Tip.x, -Tip.y) %>%
  filter(!is.na(Tip)) ->
  fullvertmeas.speciesall

fullvertmeas.speciesall
```

```{r}
fullvertmeas.speciesall <- column_to_rownames(fullvertmeas.speciesall, var="FullName")

fullvertmeas.speciesall
```

```{r}
verttree <- keep.tip(tree, tip=as.vector(fullvertmeas.speciesall$Tip))
```

```{r}
plotTree(verttree)
```

#Check if tree and data match
```{r}
length(verttree$tip.label)
nrow(fullvertmeas.speciesall)
```

```{r}
name.check(verttree, fullvertmeas.speciesall)
```

#PGLS Analysis

```{r}
pgls_d.BL<- gls(d ~ Habitat, correlation = corBrownian(phy = verttree),
                      data = fullvertmeas.speciesall, method = "ML")
summary(pgls_d.BL)
anova(pgls_d.BL)
```




























