---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(ggbeeswarm)
library(phytools)
library(FactoMineR)
library(factoextra)
library(GGally)
library(patchwork)
library(here)
library(nlme)
library(ape)
library(geiger)
library(ggtree)
library(emmeans)
library(car)
```

# Load data

```{r}
vertdata_sum <- read_csv(here("vertdata_summary.csv"))
```

## Phylogeny

This is the whole Betancur-R tree.
```{r}
tree <- read.tree(here('..', '12862_2017_958_MOESM2_ESM.tre'))
```

Get the names of species from the tree.
```{r}
allspecies <- tibble(tree$tip.label)
colnames(allspecies) <- c('FullName')
head(allspecies)
```

And split the names into family, genus, and species.
```{r}
allspecies <- 
  allspecies %>% separate(FullName, sep='_', into=c('Family', 'Genus', 'Species'), 
                          extra='drop', remove=FALSE)
```

Set up the tip number (just the row)
```{r}
allspecies$Tip <- seq_len(nrow(allspecies))
```

```{r}
vertdata <- left_join(vertdata_sum, allspecies, 
                                  by=c("MatchGenus"="Genus", "MatchSpecies"="Species")) %>%
  select(-(ends_with(".x") | ends_with(".y")))
vertdata
```

Drop species without a match
```{r}
vertdata %>%
  filter(is.na(Tip)) %>%
  distinct(Species, .keep_all=TRUE) %>%
  select(Species, MatchGenus, MatchSpecies, Tip, Habitat)
```

```{r}
vertdata <-
  vertdata %>%
  filter(!is.na(Tip))
```


```{r}
ourspecies <-
  vertdata %>%
  distinct(Species, .keep_all=TRUE)
```


```{r}
verttree <- keep.tip(tree, tip=as.vector(ourspecies$Tip))
```

```{r}
plotTree(verttree)
```


```{r}
vertdata_sp <- 
  vertdata %>%
  distinct(FullName, .keep_all = TRUE) %>%
  mutate(rowname = FullName) %>%
  column_to_rownames(var = "rowname")
```

```{r}
verttree <- keep.tip(tree, tip=as.vector(vertdata_sp$Tip))
```

```{r}
left_join(as_tibble(verttree),
          vertdata_sp %>%
            rownames_to_column("label") %>%
            select(label, Habitat)) %>%
  tidytree::as.treedata() %>%
  ggtree(layout = 'circular') + # geom_tiplab() +
  geom_tippoint(aes(color = Habitat))
```
Check if tree and data match
```{r}
length(verttree$tip.label)
nrow(vertdata_sp)
```

```{r}
name.check(verttree, vertdata_sp)
```

## PGLS Analysis for means, maxes, medians, and 80%

```{r}
vertdata_sp0 <-
  vertdata_sp %>%
  mutate(across(contains('slope') | contains('quad'), 
                ~ replace_na(., 0)))
```

```{r}
var <- c('CBL_mid', 'd_mid', 'alphaAnt_mid', 'alphaPos_mid', 'DAnt_mid', 'DPos_mid', 
         'CBL_slope', 'd_slope', 'alphaAnt_slope', 'alphaPos_slope', 'DAnt_slope', 'DPos_slope', 
         'CBL_quad', 'd_quad', 'alphaAnt_quad', 'alphaPos_quad', 'DAnt_quad', 'DPos_quad', 
         'CBL_order', 'd_order', 'alphaAnt_order', 'alphaPos_order', 'DAnt_order', 'DPos_order')

modeltests <- tibble()

for (i in seq_along(var)) {
  fmla <- as.formula(paste(var[i], "Habitat", sep = " ~ "))
  mod <- gls(fmla, correlation = corBrownian(1, phy = verttree, form = ~FullName),
                      data = vertdata_sp0, method = "ML")
  
  ava <- broom::tidy(Anova(mod))
  ava$var = var[i]
  ava$model = list(mod)
  
  modeltests <- bind_rows(modeltests, ava)
}

modeltests %>%
  dplyr::select(var, statistic, p.value, everything()) %>%
  filter(p.value < 0.05) %>%
  arrange(p.value)
```
```{r}
compare_habitats <- function(model) {
  emm <- emmeans(model, ~Habitat)
  p <- as.data.frame(pairs(emm))
  es <- as.data.frame(eff_size(emm, sigma = sigma(model), edf = model$dims$N - model$dims$p))
  p$effect.size <- es$effect.size
  
  p %>%
    mutate(contrast = str_replace(contrast, "(\\w+) - (\\w+)", "\\1_\\2")) %>%
    select(contrast, p.value, effect.size) %>%
    rename(p = p.value, eff = effect.size) %>%
    pivot_wider(names_from = contrast, values_from = c(p, eff),
                names_glue = "{contrast}_{.value}")
}
```

```{r}
modeltests %>%
  dplyr::select(var, statistic, p.value, everything()) %>%
  filter(p.value < 0.05) %>%
  mutate(mc = purrr::map(model, compare_habitats)) %>%
  unnest(mc) %>%
  mutate(total_eff = abs(benthic_demersal_eff) + abs(benthic_pelagic_eff) + abs(demersal_pelagic_eff)) %>%
  # filter(total_eff > 0.5) %>%
  relocate(total_eff, .after = p.value) %>%
  arrange(desc(total_eff))
```

## Mean plots with stats

```{r}
vertdata_sp0 %>%
  select(Habitat, d_mid, alphaPos_mid, DPosBW_quad, dBW_quad, DAntBW_slope, DAntBW_quad, DPosBW_slope, dBW_slope) %>%
  pivot_longer(cols = !Habitat, names_to = "var", values_to = "value") %>%
  filter(!is.na(var)) %>%
  ggplot(aes(x = Habitat, y = value, color = Habitat)) +
  geom_quasirandom(width=0.3) +
  geom_boxplot(width=0.3, alpha=0.5, outlier.shape = NA) +
  stat_summary(aes(group = 1), fun = "median", geom = "line") +
  facet_wrap(~ var, scales = "free_y")
```


## Pairs of species

```{r}
pairs <-
  as_tibble(verttree) %>%
  left_join(vertdata_sp0 %>%
              rownames_to_column("label") %>%
              select(label, Habitat, Family,
                     d_max, alphaPos_max)) %>%
  filter(!is.na(Habitat)) %>%
  group_by(parent) %>%
  arrange(Habitat) %>%
  mutate(nsib = n(),
         diffhab = any(Habitat != first(Habitat)),
         compare = str_c(str_sub(Habitat, start=1, end=1), collapse="-")) %>%
  ungroup() %>%
  filter(nsib == 2 & diffhab) %>%
  select(-nsib, -diffhab) %>%
  arrange(parent, Habitat)
```

```{r}
pairs <-
  pairs %>%
  pivot_longer(c(d_max, alphaPos_max), 
               names_to="var", values_to="value") %>%
  group_by(var, parent) %>%
  arrange(Habitat) %>%
  mutate(change = if_else(lead(value) > value, "increase", "decrease")) %>%
  fill(change) %>%
  mutate(change = factor(change),
         parent = factor(parent)) %>%
  ungroup() %>%
  arrange(var, parent, Habitat)
```

```{r}
pairs <-
  pairs %>%
  mutate(ptsize = round(400/branch.length),
         ptsize = if_else(ptsize > 15, 15, ptsize))
```

```{r}
pairs %>%
  # filter(str_detect(var, "mn")) %>%
  filter(var == "alphaPos_max") %>%
  ggplot(aes(x = Habitat, y = value, group=fct_cross(var, parent),
             color=compare, linetype=change, size=ptsize)) +
  geom_line(size = 1) + geom_point()
  #facet_grid(var ~ ., scales="free_y")
```

```{r}
pairs %>%
  # filter(!str_detect(var, "ctr")) %>%
  ggplot(aes(x = Habitat, y = value, group=fct_cross(var, parent),
             color=compare, size = ptsize, linetype=change)) +
  geom_line(size = 1) + geom_point(alpha = 0.7) +
  facet_grid(var ~ ., scales="free_y")
```

