---
title: "Baxter et al 2022 vertebrae analysis"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# Internal vertebral morphology of bony fishes matches the mechanical demands of different environments

Dana Baxter$^1$   |    Karly E. Cohen$^3$   |   Cassandra M. Donatelli$^2$   |    Eric D. Tytell$^1$

$^1$Tufts University, Department of Biology
$^2$University of Ottawa, Department of Biology
$^3$University of Washington, Friday Harbor Labs

Accepted at _Ecology and Evolution_ October 20, 2022.

[Abstract](about.html)

# Raw data

The initial measurements were made by Dana Baxter by clicking points on vertebrae from CT scans. The measurements are in `MasterVert_Measurements_old.csv`.

Dana processed the data from Cymatogaster aggregata a bit later, so we have to merge it into the main data set.

Input: `data/MasterVert_Measurements_old.csv`
Output: `data/MasterVert_Measurements.csv`

Here is the process to merge the Cymatogaster data: [01-ProcessCymatogasterFiles](01-ProcessCymatogasterFiles.html).


# Matching species

Species are distributed somewhat randomly throughout the bony fishes. We use the phylogeny from Betancur-R et al 2017. Not every species we digitized is in their tree. For most of them, we can use another species in the same genus, since we don't have many species in our data set that are in one genus.

Input: `data/MasterVert_Measurements.csv`
Output: `output/MasterVert_Measurements_Matched.csv`
   This contains all of the measurements for all of the vertebrae, but with a new set of columns for "MatchSpecies" and "MatchGenus", which are the matching species in the Betancur-R tree.

This notebook checks the match between our species and the one in the tree: [02-CheckSpeciesMatch](02-CheckSpeciesMatch.html).

# Summary data sets

## Centering and taking maxes and medians

Here, we take the data for each vertebra and produce summary values for each species. We first center the data set by finding the median value of any measurement for each vertebra across all of the species, then subtracting the actual value from that median.

Input: `output/MasterVert_Measurements_Matched.csv`
Output: 

* `output/vertdata_centered.csv`: This contains the centered measurements
* `output/vertdata_summary.csv`: This contains the summary maximum values and medians for each species

[Notebook](03-summarize_vert_meas.html)


# Merge the phylogeneny

First, we need to merge our data set with an existing phylogeny. We use the phylogeny from Fish Tree of Life: https://fishtreeoflife.org/. (Daniel L. Rabosky*, Jonathan Chang*, Pascal O. Title*, Peter F. Cowman, Lauren Sallan, Matt Friedman, Kristin Kaschner, Cristina Garilao, Thomas J. Near, Marta Coll, Michael E. Alfaro* (2018). An inverse latitudinal gradient in speciation rate for marine fishes. Nature, 559(7714), 392–395 doi:10.1038/s41586-018-0273-1)

Input: `data/actinopt_12k_treePL.tre.xz`,
  `output/vertdata_summary.csv`
Output: 

* `output/vertdata_summary_species.csv`: Summary data with matched tips and labels from the phylogenetic tree.
* `output/vert_tree.rds`: The phylogeny containing just our species in RData format. The CSV export wasn't working properly for tree data

[Notebook](11-MergePhylogeny.html)

# Run the statistics

This script runs all of the PGLS analysis and generates most of the output tables and figures.

[Notebook](12-VertPGLS2.html)

Input: `output/MasterVert_Measurements_Matched.csv`,
  `output/vertdata_summary_species.csv`
  `output/vert_tree.rds`
Output: 

* `output/habitatvals.csv`: Predicted values for the morphological parameters in each habitat
* `output/effectsizes.csv`: Effect sizes for differences in habitats
* `output/anovatabs.csv`: Anova table

# Figures

## Figure 1: Shows the phylogeny and several example vertabrae.

This produces the phylogeny.

[Notebook](20-plot_phylogeny.html)

## Figure 3, 4, 5

Figures showing the distribution of fineness across habitats, the means of all the morphological parameters as a function of habitat and fineness, and the mean shape of the vertebrae based on the measurements.

Also generates the stats table.

[Notebook](21-plot_fits_and_summary.html)
