---
title: "License"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# Code

Analysis of vertebral morphology using phylogenetic generalized least squares.

Copyright (C) 2022. Eric D. Tytell, Dana Baxter, Karly E. Cohen, Cassandra Donatelli

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.


# Text

Text in these notebooks and the text of the manuscript are licensed under a [Creative Commons Attribution License](https://creativecommons.org/licenses/by/4.0/) (CC BY). which allows users to copy, distribute and transmit an article, adapt the article and make commercial use of the article. The CC BY license permits commercial and non-commercial re-use of an open access article, as long as the author is properly attributed.
